const SET_MESSAGES = "SET_MESSAGES";

const CAR_CONFIGTYPES_DATA_FETCH_REQUESTED = "CAR_CONFIGTYPES_DATA_FETCH_REQUESTED";
const CAR_CONFIGTYPES_DATA_FETCH_FAILED = "CAR_CONFIGTYPES_DATA_FETCH_FAILED";
const CAR_CONFIGTYPES_DATA_FETCH_SUCCEEDED = "CAR_CONFIGTYPES_DATA_FETCH_SUCCEEDED";

const CAR_TYPES_DATA_FETCH_REQUESTED = "CAR_TYPES_DATA_FETCH_REQUESTED";
const CAR_TYPES_DATA_FETCH_FAILED = "CAR_TYPES_DATA_FETCH_FAILED";
const CAR_TYPES_DATA_FETCH_SUCCEEDED = "CAR_TYPES_DATA_FETCH_SUCCEEDED";

const BESTELLUNGEN_DATA_FETCH_REQUESTED = "BESTELLUNGEN_DATA_FETCH_REQUESTED";
const BESTELLUNGEN_DATA_FETCH_FAILED = "BESTELLUNGEN_DATA_FETCH_FAILED";
const BESTELLUNGEN_DATA_FETCH_SUCCEEDED = "BESTELLUNGEN_DATA_FETCH_SUCCEEDED";

const BESTELLUNGEN_DATA_DELETE_REQUESTED = "BESTELLUNGEN_DATA_DELETE_REQUESTED";
const BESTELLUNGEN_DATA_DELETE_FAILED = "BESTELLUNGEN_DATA_DELETE_FAILED";
const BESTELLUNGEN_DATA_DELETE_SUCCEEDED = "BESTELLUNGEN_DATA_DELETE_SUCCEEDED";

const BESTELLUNGEN_DATA_POST_REQUESTED = "BESTELLUNGEN_DATA_POST_REQUESTED";
const BESTELLUNGEN_DATA_POST_FAILED = "BESTELLUNGEN_DATA_POST_FAILED";
const BESTELLUNGEN_DATA_POST_SUCCEEDED = "BESTELLUNGEN_DATA_POST_SUCCEEDED";


export {
  SET_MESSAGES,

  // for configtypefetch all, by id, by name
  CAR_CONFIGTYPES_DATA_FETCH_REQUESTED,
  CAR_CONFIGTYPES_DATA_FETCH_FAILED,
  CAR_CONFIGTYPES_DATA_FETCH_SUCCEEDED,

  // for cars/all fetch
  CAR_TYPES_DATA_FETCH_REQUESTED,
  CAR_TYPES_DATA_FETCH_FAILED,
  CAR_TYPES_DATA_FETCH_SUCCEEDED,

  // for get bestellungen fetch
  BESTELLUNGEN_DATA_FETCH_REQUESTED,
  BESTELLUNGEN_DATA_FETCH_FAILED,
  BESTELLUNGEN_DATA_FETCH_SUCCEEDED,

  // for delete bestellungen fetch
  BESTELLUNGEN_DATA_DELETE_REQUESTED,
  BESTELLUNGEN_DATA_DELETE_FAILED,
  BESTELLUNGEN_DATA_DELETE_SUCCEEDED,

  // for post bestellungen fetch
  BESTELLUNGEN_DATA_POST_REQUESTED,
  BESTELLUNGEN_DATA_POST_FAILED,
  BESTELLUNGEN_DATA_POST_SUCCEEDED,
};
