const ENVIRONMENT = {
  LOCATION: process.env.NODE_ENV,
  CAR_CONFIGURATOR_API_URL: process.env.CAR_CONFIGURATOR_API_URL,
  WEATHER_API_KEY: process.env.WEATHER_API_KEY,
};

export default ENVIRONMENT;
